name: Actions Runner Controller Demo
on:
  workflow_dispatch:

jobs:
  Explore-GitHub-Actions-1:
    # You need to use the INSTALLATION_NAME from the previous step
    runs-on: arc-runner-set
    steps:
    - run: echo "ðŸŽ‰ This job uses runner scale set runners!"
    - run: sleep 60
  Explore-GitHub-Actions-2:
    # You need to use the INSTALLATION_NAME from the previous step
    runs-on: arc-runner-set
    steps:
    - run: echo "ðŸŽ‰ This job uses runner scale set runners!"
    - run: sleep 60
  Explore-GitHub-Actions-3:
    # You need to use the INSTALLATION_NAME from the previous step
    runs-on: arc-runner-set
    steps:
    - run: echo "ðŸŽ‰ This job uses runner scale set runners!"
    - run: sleep 60
  Explore-GitHub-Actions-4:
    # You need to use the INSTALLATION_NAME from the previous step
    runs-on: arc-runner-set
    steps:
    - run: echo "ðŸŽ‰ This job uses runner scale set runners!"
    - run: sleep 60
  Explore-GitHub-Actions-5:
    # You need to use the INSTALLATION_NAME from the previous step
    runs-on: arc-runner-set
    steps:
    - run: echo "ðŸŽ‰ This job uses runner scale set runners!"
    - run: sleep 60
